Repository jenkins-x/gsm-controller, pull requests merged in 2024-03, with the labels that each got.

#28 chore: remove resource requests from step templates
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S, ok-to-test

#30 fix: change to default changelog step
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S

#29 chore: bump go version from 1.12 to 1.19
  go.mod
  go.sum
Labels: approved, size/L, ok-to-test

#24 feat: add subscribe command to follow Secret Manager Event Notifications
  README.md
  charts/gsm-controller/templates/cronjob.yaml
  charts/gsm-controller/templates/deployment.yaml
  charts/gsm-controller/templates/role.yaml
  charts/gsm-controller/templates/rolebinding.yaml
  charts/gsm-controller/values.yaml
  cmd/root/root.go
  go.mod
  go.sum
  pkg/secrets.go
  pkg/subscribe.go
  pkg/subscribe_test.go
  pkg/watch.go
Labels: approved, size/L, ok-to-test
